version: "3"
services:
  rpi:
    build: ./rpi
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
      - "/dev/ttyACM2:/dev/ttyACM2"
      - "/dev/ttyACM3:/dev/ttyACM3"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
      - "/dev/ttyUSB2:/dev/ttyUSB2"
      - "/dev/ttyUSB3:/dev/ttyUSB3"
      - "/dev/vchiq:/dev/vchiq"
    privileged: true
    environment:
      - TZ=Asia/Tokyo
      - LD_LIBRARY_PATH=/opt/vc/lib
    volumes:
      - ./share:/share_host
      - /opt/vc:/opt/vc

